### ISSUE TITLE
Unable to make package on pnrsender

### ISSUE THREAD

**Issue by Supposedly-Sam** [AwesomeIndustry/SIMLessPNRGateway#1]
It gives me the error message `
Tweak.x:6:9: fatal error:  
Tweak.x:6:9: fatal error: 'MRYIPCCenter.h' file not found  
#import <MRYIPCCenter.h>  
        ^~~~~~~~~~~~~~~~  
1 error generated.`

**Comment by AwesomeIndustry** [comment]
Oh, I think you'll need to install [MRYIPC](https://github.com/Muirey03/MRYIPC) in your Theos installation. Thanks for the catch!
I'll update the README to include that
