### ISSUE TITLE
Typo in Tweak.x for pnrsender

### ISSUE THREAD

**Issue by Supposedly-Sam** [AwesomeIndustry/SIMLessPNRGateway#2]
==> Compiling Tweak.x (arm64)…
Tweak.x:456:16: error: use of undeclared identifier 'DUMY_IMSI'; did you mean 'DUMMY_IMSI'?
        return DUMY_IMSI;
               ^~~~~~~~~
               DUMMY_IMSI
Tweak.x:14:18: note: 'DUMMY_IMSI' declared here
NSString * const DUMMY_IMSI = @"310410777777778";
                 ^

**Comment by AwesomeIndustry** [comment]
Thanks for the update--I just realized I forgot to upload my latest changes. Should be all fixed now
