### ISSUE TITLE
ld: library not found for -lmryipc for pnrsender`

### ISSUE THREAD

**Issue by Supposedly-Sam** [AwesomeIndustry/SIMLessPNRGateway#3]
> Making all for tweak PNRSender…
==> Preprocessing Tweak.x…
==> Compiling Tweak.x (arm64)…
==> Linking tweak PNRSender (arm64)…
ld: library not found for -lmryipc
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by AwesomeIndustry** [comment]
Huh, that's strange. Does your `$THEOS/include` contain a `MRYIPCCenter.h` and your `$THEOS/lib` contain a `libmryipc.dylib`?

**Comment by Supposedly-Sam** [comment]
It does now

**Comment by iswheeler** [comment]
Ok, I'll try reinstalling theos to see if the error shows up again.
Also, I just added this in the README but figured I'd mention it here too--you'll need to create a text file in the root directory of your iPhone (`/pnr_android_number.txt`) with the contents being the international format of your Android phone's number (ex. `+11234567890`)

**Comment by iswheeler** [comment]
Huh, just reinstalled theos and re-added MRYIPC to `$THEOS` and it appears to compile ok:

```
(base) █ [.../pnrsender] > make package       
> Making all for tweak PNRSender…
==> Preprocessing Tweak.x…
==> Compiling Tweak.x (arm64)…
==> Linking tweak PNRSender (arm64)…
==> Generating debug symbols for PNRSender…
==> Merging tweak PNRSender…
==> Signing PNRSender…
> Making stage for tweak PNRSender…
dm.pl: building package `dev.altavision.pnrsender:iphoneos-arm' in `./packages/dev.altavision.pnrsender_0.0.1-92+debug_iphoneos-arm.deb'
```

Does re-cloning and rebuilding work?
