### ISSUE TITLE
unable to make PNRSender: undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by Supposedly-Sam** [AwesomeIndustry/SIMLessPNRGateway#4]
ld: warning: ignoring file /home/sam/theos/lib/libmryipc.dylib, building for iOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x40 0x69 0x6E 0x74 0x65 0x72 0x66 0x61 0x63 0x65 0x20 0x4D 0x52 0x59 0x49 0x50 )
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MRYIPCCenter", referenced from:
      objc-class-ref in Tweak.x.019e5e8c.o
ld: symbol(s) not found for architecture arm64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/home/sam/theos/makefiles/instance/library.mk:52: /home/sam/SIMLessPNRGateway/pnrsender/.theos/obj/debug/arm64/PNRSender.dylib] Error 1
make[2]: *** [/home/sam/theos/makefiles/instance/library.mk:52: /home/sam/SIMLessPNRGateway/pnrsender/.theos/obj/debug/arm64/PNRSender.dylib] Error 2
make[1]: *** [/home/sam/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/home/sam/theos/makefiles/master/rules.mk:152: PNRSender.all.tweak.variables] Error 2

**Comment by iswheeler** [comment]
Just noticed your working dir is in `/home/`--are you trying to build on linux?

**Comment by Supposedly-Sam** [comment]
yeah, im using wsl

**Comment by Supposedly-Sam** [comment]
Should I try to build this on my mac?

**Comment by iswheeler** [comment]
Yeah, that'll probably work better if you have access to a mac. I'm working on setting it up in WSL right now too

**Comment by iswheeler** [comment]
Huh, just installed it in WSL (Ubuntu 20.04.2 LTS) and it compiled just fine after installing MRYIPC in Theos. What WSL version are you using?

**Comment by Supposedly-Sam** [comment]
Ubuntu 22.04.1 LTS

**Comment by Supposedly-Sam** [comment]
what version of MRYIPC are you using (did you git clone MRYIPC and copy from there)

**Comment by iswheeler** [comment]
Yeah, I just downloaded the latest version

**Comment by Supposedly-Sam** [comment]
Couldn't you just upload the pnrsender deb as a release now that you don't need to modify the code with your phonenumber?

**Comment by iswheeler** [comment]
Oh, I thought I'd already uploaded it to releases. Should be fixed now

**Comment by Supposedly-Sam** [comment]
I hadn't checked

**Comment by iswheeler** [comment]
That's really strange--I just installed Ubuntu 22.04.2 LTS in WSL and I'm still not getting any compilation errors. Do you have WSL 2 turned on?

**Comment by Supposedly-Sam** [comment]
Yes
